### ISSUE TITLE
Discord invite link is invalid

### ISSUE THREAD

**Issue by schkwve** [xt-sys/exectos#1]
Sorry for opening an unrelated issue, but I'd like to speak to you and couldn't find a way to contact you elsewhere.

**Comment by belliash** [comment]
The chat shield visible at the top of the README contains a valid Discord invitation. Unfortunately, when I was updating it last time, I have forgotten to update the link at the bottom, in the 'Contact' paragraph. Fixed with efcb8c8a73856130faf9fe45dafe95e42e70b27c.
